Try to avoid port problems on unbound
It was probably caused by race condition, where old unbound didn't have
enough time to terminate yet and the new one was already started. Try to
lower the chance of race condition by adding sleep.

diff --git a/net/unbound/files/unbound-init b/net/unbound/files/unbound-init
--- a/net/unbound/files/unbound-init
+++ b/net/unbound/files/unbound-init
@@ -125,7 +125,10 @@ start() {
     mkdir -p $(dirname "$CONFIGFILE")
 
     init_unbound
-    unbound
+    unbound || (
+        sleep 2 # There are temporary failures with ports in unbound sometimes, try again after a while
+	unbound
+    )
 }
 
 reload() {
@@ -151,4 +154,5 @@ stop() {
     if [ -f "$pidfile" ] ; then
         kill $(cat $pidfile) && rm "$pidfile"
     fi
+    sleep 1 # For cleanup of ports and such
 }
