unbound: add support for DNS-over-TLS

diff --git a/net/unbound/files/unbound-init b/net/unbound/files/unbound-init
--- a/net/unbound/files/unbound-init
+++ b/net/unbound/files/unbound-init
@@ -169,7 +169,7 @@ init_unbound() {
 
     if [ "$ignore_root_key" = "0" ] ; then
         set_rootkey keyfile
-	add_parameter "$ROOTKEYFILE" "auto-trust-anchor-file"
+        add_parameter "$ROOTKEYFILE" "auto-trust-anchor-file"
     fi
 
     set_parameter msg_buffer_size msg-buffer-size 8192
@@ -253,7 +253,12 @@ init_unbound() {
 
     local do_forward
     config_get_bool do_forward common forward_upstream 1
+    config_get forward_dns common forward_custom
 
+    #check custom forwarding
+    if [ -n "$forward_dns" ]; then
+        dns_config_load "$forward_dns"
+    else
     if [ "$do_forward" = "1" ] ; then
         local SERVERS
         SERVERS=$(sed -ne 's/^nameserver \(.*\)/\1/p' /tmp/resolv.conf.auto | sort)
@@ -269,12 +274,166 @@ init_unbound() {
         fi
         md5sum /tmp/resolv.conf.auto | cut -f1 -d\ >/tmp/resolv.conf.auto.last.md5
     fi
+    fi
+}
+
+dns_option_get() {
+    local ret_val var_name val
+    var_name=$1
+    config=$2
+
+    val=$(eval echo \$$1)
+    config_get ret_val "$config" "$var_name"
+
+    #rewrite variable if it's defined in uci
+    if [ ! -z "$ret_val" ]; then
+        eval export $var_name=\"$ret_val\"
+    fi
+}
+
+handle_dns_config_load() {
+    local name description enable_tls port ipv4 ipv6 pin_sha256 hostname
+    local net_ipv6 net_ipv4
+    local config="$1"
+    local config_name="$2"
+
+    config_get name "$config" "name"
+
+    #check config name (because of foreach function)
+    if [ "$name" != "$config_name" ]; then
+        echo -ne "ERR "
+        return 1
+    fi
+
+    #first load options from config and then eventualy
+    #rewrite set options from uci config
+
+    config_file=/etc/resolver/dns_servers/${config_name}.conf
+    if [ -f "$config_file" ]; then
+        source $config_file
+    fi
+
+    dns_option_get description $config
+    dns_option_get enable_tls $config
+    dns_option_get port $config
+    dns_option_get ipv4 $config
+    dns_option_get ipv6 $config
+    dns_option_get pin_sha256 $config
+    dns_option_get hostname $config
+
+    config_get net_ipv6 "common" "net_ipv6" 1
+    config_get net_ipv4 "common" "net_ipv4" 1
+
+    print_dns_config  "$name" "$description" "$enable_tls" "$port" "$ipv4" "$ipv6" "$pin_sha256" "$hostname" "$net_ipv4" "$net_ipv6"
+
+    echo -ne "OK " #
+    return 0
+}
+
+
+print_dns_config() {
+    local name description enable_tls port ipv4 ipv6 pin_sha256 hostname
+    local net_ipv6 net_ipv4
+
+    name="$1"
+    description="$2"
+    enable_tls="$3"
+    port="$4"
+    ipv4="$5"
+    ipv6="$6"
+    pin_sha256="$7"
+    hostname="$8"
+    net_ipv4="$9"
+    net_ipv6="$10"
+
+    if   [ "$net_ipv4" == "1" ] && [ "$net_ipv6" == "1" ]; then
+        if [ ! -z "$ipv4" ] && [ ! -z "$ipv6" ]; then
+            ip_list="$ipv4 $ipv6"
+        elif [ ! -z "$ipv4" ] && [ -z "$ipv6" ]; then
+            ip_list="$ipv4"
+        elif [ -z "$ipv4" ] && [ ! -z "$ipv6" ]; then
+            ip_list="$ipv6"
+        else
+            echo "Error ipv4 and ipv6 not set !"
+            exit -1
+        fi
+    elif [ "$net_ipv4" == "0" ] && [ "$net_ipv6" == "1" ]; then
+        if [ ! -z "$ipv6" ]; then
+            ip_list="$ipv6"
+        else
+            echo "Error ipv6 not set !"
+            exit 1
+        fi
+    elif [ "$net_ipv4" == "1" ] && [ "$net_ipv6" = "0" ]; then
+        if [ ! -z "$ipv4" ]; then
+            ip_list="$ipv4"
+        else
+            echo "Error ipv4 not set !"
+            exit 1
+        fi
+    else
+        echo "net_ipv4=$net_ipv4 net_ipv6=$net_ipv6"
+        echo "Error cannot choose IP address because of net_ipv4 and net_ipv6 settings!"
+        exit 1
+        fi
+
+    #set forwarding
+    echo "forward-zone:">>$CONFIGFILE
+    echo '	name: "."'>>$CONFIGFILE
+    if [ "$enable_tls" == "1" ]; then
+        echo "	forward-ssl-upstream: yes">>$CONFIGFILE
+    else
+        echo "	forward-ssl-upstream: no">>$CONFIGFILE
+    fi
+
+    for ip in $ip_list
+    do
+
+        if [ ! -z "$ip" ]; then
+            #check nonstandard port
+            if [ "$port" == "853" ] || [ -z "$port" ]; then
+                echo "	forward-addr: $ip@853" >> $CONFIGFILE
+            else
+                echo "	forward-addr: $ip@$port" >> $CONFIGFILE
+            fi
+        fi
+    done
+    if [ "$enable_tls" == "1" ]; then
+        echo "	forward-ssl-upstream: yes">>$CONFIGFILE
+    else
+        echo "	forward-ssl-upstream: no">>$CONFIGFILE
+    fi
+}
+
+dns_config_load() {
+    local config_name config_file ret
+    local name description enable_tls port ipv4 ipv6 pin_sha256 hostname
+    local net_ipv4 net_ipv6
+
+    config_name="$1"
+    config_file="/etc/resolver/dns_servers/${config_name}.conf"
+    config_load resolver
+    ret=$(config_foreach handle_dns_config_load dns_server "$config_name")
+
+    #uci part nof found, check file
+    if [ "$?" == "1" ] && [ -f "$config_file" ]; then
+        enable_tls="0" #set default value
+        config_get net_ipv6 "common" "net_ipv6" 1
+        config_get net_ipv4 "common" "net_ipv4" 1
+
+        echo "loading file from ... $config_file"
+        source $config_file
+        echo print_dns_config  "$name" "$description" "$enable_tls" "$port" "$ipv4" "$ipv6" "$pin_sha256" "$hostname" "$net_ipv4" "$net_ipv6"
+        print_dns_config  "$name" "$description" "$enable_tls" "$port" "$ipv4" "$ipv6" "$pin_sha256" "$hostname" "$net_ipv4" "$net_ipv6"
+    fi
+    #echo "ret_value_dns_load=$ret"
 }
 
 start() {
 
     mkdir -p $(dirname "$CONFIGFILE")
     chown $USERNAME:$GROUP $(dirname "$CONFIGFILE")
+    [ -f /etc/unbound/named.cache ] && chmod o+r /etc/unbound/named.cache
 
     init_unbound
     if [ -e /usr/sbin/unbound-checkconf ] ; then
@@ -291,6 +450,7 @@ reload() {
 
     mkdir -p $(dirname "$CONFIGFILE")
     chown $USERNAME:$GROUP $(dirname "$CONFIGFILE")
+    [ -f /etc/unbound/named.cache ] && chmod o+r /etc/unbound/named.cache
 
     init_unbound
 
