switch-branch: ensure that reinstall happens on branch switch
This changes original code that just executed updater with reinstall-all
option with more clever code in Lua to detect when we have to reinstall
and when it is not required to reinstall everything.
This fixes situation when updater fails and user later does not run
pkgupdate --reinstall-all. This sets it so even if updater is run
outside of switch-branch script the switch is detected and reinstall
performed.

diff --git a/updater/switch-branch/files/switch-branch b/updater/switch-branch/files/switch-branch
--- a/updater/switch-branch/files/switch-branch
+++ b/updater/switch-branch/files/switch-branch
@@ -258,6 +258,11 @@ set -x
 
 ## Set uci configuration
 uci set updater.turris=turris
+if [ "$(get_mode)" = "branch" ]; then
+	uci set updater.turris.switch_from="$(get_branch)"
+else
+	uci set updater.turris.switch_from="hbs"
+fi
 if [ "$version" = "y" ]; then
 	uci set updater.turris.mode="version"
 	uci set updater.turris.version="$branch"
@@ -280,14 +285,11 @@ if [ "$verify" = "y" ]; then
 	exit 0
 fi
 
-## Run updater
-updater_args=
-config_get_bool updater_approvals autorun approvals 0
-[ "$updater_approvals" = "1" ] || updater_args="--batch"
-pkgupdate --reinstall-all $updater_args || echo "Updater execution exited with error. Please see previous output to know what went wrong." >&2
-
 ## Update opkg
 opkg update || echo "OPKG update failed. Please see previous output to know what went wrong." >&2
+
+## Run updater
+updater-supervisor -d --ensure-run || echo "Updater failed to start. Please run it manualy: pkgupdate" >&2
 
 set +x
 
