switch-branch: print error message about invalid option
This adds error message when argument looks like option but is unknown
to immediately fail. To keep backward support as untouched as we can the
standard -- argument is introduced to disable options processing while
at the same time allowing options to be used after branch if -- was not
used.

diff --git a/updater/switch-branch/files/switch-branch b/updater/switch-branch/files/switch-branch
--- a/updater/switch-branch/files/switch-branch
+++ b/updater/switch-branch/files/switch-branch
@@ -104,8 +104,12 @@ check_version() {
 
 ##################################################################################
 
+print_usage() {
+	echo "Usage: switch-branch [OPTION]... [--] [BRANCH]"
+}
+
 print_help() {
-	echo "Usage: switch-branch [OPTION]... [BRANCH]"
+	print_usage
 	echo "Script for easier switching between rolling versions of Turris OS."
 	echo "It configures both updater-ng and opkg repository source."
 	echo
@@ -178,13 +182,14 @@ select_version() {
 }
 
 ##################################################################################
-
 target=
 mode=
 list_versions="n"
 verify="n"
 force="n"
-while [ $# -gt 0 ]; do
+noopts="n"
+
+arg_option() {
 	case "$1" in
 		-h|--help)
 			print_help
@@ -205,10 +210,33 @@ while [ $# -gt 0 ]; do
 		--force)
 			force="y"
 			;;
+		--)
+			noopts="y"
+			;;
 		*)
-			target="$1"
+			echo "Invalid option: $1" >&2
+			print_usage
+			exit 1
 			;;
 	esac
+}
+
+while [ $# -gt 0 ]; do
+	if [ "$noopts" != "y" ]; then
+		case "$1" in
+			-*)
+				arg_option "$1"
+				shift
+				continue
+				;;
+		esac
+	fi
+	[ -z "$target" ] || {
+		echo "Invalid argument: $1" >&2
+		print_usage
+		exit 1
+	}
+	target="$1"
 	shift
 done
 
