mwan3: update to the version 2.6.18
Fixes turris/turris-os-packages#187

diff --git a/net/mwan3/files/usr/sbin/mwan3 b/net/mwan3/files/usr/sbin/mwan3
--- a/net/mwan3/files/usr/sbin/mwan3
+++ b/net/mwan3/files/usr/sbin/mwan3
@@ -1,12 +1,7 @@
 #!/bin/sh
 
-[ -x /usr/sbin/ip ] || exit 4
-[ -x /usr/sbin/ipset ] || exit 5
-[ -x /usr/sbin/iptables ] || exit 6
-[ -x /usr/sbin/ip6tables ] || exit 7
-[ -x /usr/bin/logger ] || exit 8
-
 . /lib/functions.sh
+. /usr/share/libubox/jshn.sh
 . /lib/functions/network.sh
 . /lib/mwan3/mwan3.sh
 
@@ -19,13 +14,13 @@ Available commands:
 	start           Load iptables rules, ip rules and ip routes
 	stop            Unload iptables rules, ip rules and ip routes
 	restart         Reload iptables rules, ip rules and ip routes
-        ifup <iface>    Load rules and routes for specific interface
-        ifdown <iface>  Unload rules and routes for specific interface
-        interfaces      Show interfaces status
-        policies        Show currently active policy
-	connected	Show directly connected networks
-        rules           Show active rules
-        status          Show all status
+	ifup <iface>    Load rules and routes for specific interface
+	ifdown <iface>  Unload rules and routes for specific interface
+	interfaces      Show interfaces status
+	policies        Show currently active policy
+	connected       Show directly connected networks
+	rules           Show active rules
+	status          Show all status
 
 EOF
 }
@@ -42,15 +37,13 @@ ifdown()
 
 	ACTION=ifdown INTERFACE=$1 /sbin/hotplug-call iface
 
-	if [ -e /var/run/mwan3track-$1.pid ] ; then
-		kill $(cat /var/run/mwan3track-$1.pid)
-		rm /var/run/mwan3track-$1.pid
-	fi
+	kill $(pgrep -f "mwan3track $1 $2") &> /dev/null
+	mwan3_track_clean $1
 }
 
 ifup()
 {
-	local device enabled
+	local device enabled up l3_device
 
 	config_load mwan3
 
@@ -62,12 +55,20 @@ ifup()
 		echo "Too many arguments. Usage: mwan3 ifup <interface>" && exit 0
 	fi
 
+	config_get_bool enabled globals 'enabled' 0
+	[ ${enabled} -gt 0 ] || {
+		echo "Warning: mwan3 is global disabled. Usage: /etc/init.d/mwan3 start"
+		exit 0
+	}
+
+	json_load $(ubus -S call network.interface.$1 status)
+	json_get_vars up l3_device
 	config_get enabled "$1" enabled 0
 
-	device=$(uci -p /var/state get network.$1.ifname) &> /dev/null
-
-	if [ -n "$device" ] ; then
-		[ "$enabled" -eq 1 ] && ACTION=ifup INTERFACE=$1 DEVICE=$device /sbin/hotplug-call iface
+	if [ "$up" -eq 1 ] \
+		&& [ -n "$l3_device" ] \
+		&& [ "$enabled" -eq 1 ]; then
+		ACTION=ifup INTERFACE=$1 DEVICE=$l3_device /sbin/hotplug-call iface
 	fi
 }
 
@@ -120,20 +121,52 @@ status()
 
 start()
 {
+	local enabled src_ip local_source
+
 	config_load mwan3
+	config_get_bool enabled globals 'enabled' 0
+	[ ${enabled} -gt 0 ] || {
+		echo "Warning: mwan3 is global disabled. Usage: /etc/init.d/mwan3 start"
+		exit 0
+	}
+
+	config_get local_source globals local_source 'none'
+	[ "${local_source}" = "none" ] || {
+		src_ip=$(uci_get_state mwan3 globals src_ip)
+		[ "${src_ip}" != "" ] && {
+			ip route del default via "${src_ip}" dev lo 1>/dev/null 2>&1
+			ip addr del "${src_ip}/32" dev lo 1>/dev/null 2>&1
+		}
+
+		network_get_ipaddr src_ip "${local_source}"
+		if [ "${src_ip}" = "" ]; then
+			$LOG warn "Unable to set source ip for own initiated traffic (${local_source})"
+		else
+			ip addr add "${src_ip}/32" dev lo
+			ip route add default via "${src_ip}" dev lo
+			uci_toggle_state mwan3 globals src_ip "${src_ip}"
+		fi
+	}
+
 	config_foreach ifup interface
 }
 
 stop()
 {
-	local ipset route rule table IP IPT
+	local ipset route rule table IP IPT pid src_ip
 
-	killall mwan3track &> /dev/null
-	rm /var/run/mwan3track-* &> /dev/null
+	for pid in $(pgrep -f "mwan3track"); do
+		kill -TERM "$pid" > /dev/null 2>&1
+		sleep 1
+		kill -KILL "$pid" > /dev/null 2>&1
+	done
+
+	config_load mwan3
+	config_foreach mwan3_track_clean interface
 
 	for IP in "$IP4" "$IP6"; do
 
-		for route in $($IP route list table all | sed 's/.*table \([^ ]*\) .*/\1/' |  awk '{print $1}' | awk '{for(i=1;i<=NF;i++) if($i+0>0) if($i+0<255) {print;break}}'); do
+		for route in $(seq 1 $MWAN3_INTERFACE_MAX); do
 			$IP route flush table $route &> /dev/null
 		done
 
@@ -163,6 +196,15 @@ stop()
 	for ipset in $($IPS -n list | grep mwan3 | grep -E '_v4|_v6'); do
 		$IPS -q destroy $ipset
 	done
+
+	mwan3_lock_clean
+	rm -rf $MWAN3_STATUS_DIR $MWAN3TRACK_STATUS_DIR
+
+	src_ip=$(uci_get_state mwan3 globals src_ip)
+	[ "${src_ip}" = "" ] || {
+		ip route del default via "${src_ip}" dev lo 1>/dev/null 2>&1
+		ip addr del "${src_ip}/32" dev lo 1>/dev/null 2>&1
+	}
 }
 
 restart() {
@@ -172,6 +214,7 @@ restart() {
 
 case "$1" in
 	ifup|ifdown|interfaces|policies|connected|rules|status|start|stop|restart)
+		mwan3_init
 		$*
 	;;
 	*)
