mwan3: update to version 2.7.10

diff --git a/net/mwan3/files/usr/sbin/mwan3 b/net/mwan3/files/usr/sbin/mwan3
--- a/net/mwan3/files/usr/sbin/mwan3
+++ b/net/mwan3/files/usr/sbin/mwan3
@@ -1,11 +1,5 @@
 #!/bin/sh
 
-# [ -x /usr/sbin/ip ] || exit 4
-# [ -x /usr/sbin/ipset ] || exit 5
-# [ -x /usr/sbin/iptables ] || exit 6
-# [ -x /usr/sbin/ip6tables ] || exit 7
-# [ -x /usr/bin/logger ] || exit 8
-
 . /lib/functions.sh
 . /usr/share/libubox/jshn.sh
 . /lib/functions/network.sh
@@ -66,6 +60,12 @@ ifup()
 	if [ -n "$2" ]; then
 		echo "Too many arguments. Usage: mwan3 ifup <interface>" && exit 0
 	fi
+
+	#config_get_bool enabled globals 'enabled' 0
+	#[ ${enabled} -gt 0 ] || {
+	#	echo "Warning: mwan3 is global disabled. Usage: /etc/init.d/mwan3 start"
+	#	exit 0
+	#}
 
 	status=$(ubus -S call network.interface.$1 status)
 	[ -n "$status" ] && {
@@ -135,12 +135,32 @@ start()
 
 	uci_toggle_state mwan3 globals enabled "1"
 
+	#config_get local_source globals local_source 'none'
+	#[ "${local_source}" = "none" ] || {
+	#	src_ip=$(uci_get_state mwan3 globals src_ip)
+	#	[ "${src_ip}" != "" ] && {
+	#		ip route del default via "${src_ip}" dev lo 1>/dev/null 2>&1
+	#		ip addr del "${src_ip}/32" dev lo 1>/dev/null 2>&1
+	#	}
+	#
+	#	network_get_ipaddr src_ip "${local_source}"
+	#	if [ "${src_ip}" = "" ]; then
+	#		$LOG warn "Unable to set source ip for own initiated traffic (${local_source})"
+	#	else
+	#		ip addr add "${src_ip}/32" dev lo
+	#		ip route add default via "${src_ip}" dev lo
+	#		uci_toggle_state mwan3 globals src_ip "${src_ip}"
+	#	fi
+	#}
+
 	config_foreach ifup interface
 }
 
 stop()
 {
 	local ipset route rule table IP IPT pid
+
+	mwan3_lock "command" "mwan3"
 
 	for pid in $(pgrep -f "mwan3rtmon"); do
 		kill -TERM "$pid" > /dev/null 2>&1
@@ -190,8 +210,16 @@ stop()
 		$IPS -q destroy $ipset
 	done
 
+	mwan3_unlock "command" "mwan3"
+
 	mwan3_lock_clean
 	rm -rf $MWAN3_STATUS_DIR $MWAN3TRACK_STATUS_DIR
+
+	#src_ip=$(uci_get_state mwan3 globals src_ip)
+	#[ "${src_ip}" = "" ] || {
+	#	ip route del default via "${src_ip}" dev lo 1>/dev/null 2>&1
+	#	ip addr del "${src_ip}/32" dev lo 1>/dev/null 2>&1
+	#}
 
 	uci_toggle_state mwan3 globals enabled "0"
 }
