knot-resolver: add DNS-over-TLS support

diff --git a/net/knot-resolver/files/kresd.init b/net/knot-resolver/files/kresd.init
--- a/net/knot-resolver/files/kresd.init
+++ b/net/knot-resolver/files/kresd.init
@@ -21,7 +21,7 @@ check_root_key() {
 }
 
 service_triggers() {
-        procd_add_reload_trigger "dhcp"
+	procd_add_reload_trigger "dhcp"
 }
 
 add_listen_addr() {
@@ -77,6 +77,7 @@ include_custom_config() {
 
 load_uci_config_common() {
 	local interface keyfile verbose port msg_buffer_size net_ipv4 net_ipv6 msg_cache_size do_forward ignore_root_key keep_cache_bool
+	local forward_dns
 	local section="common"
 
 	# port
@@ -135,19 +136,26 @@ load_uci_config_common() {
 	fi
 
 	config_get_bool do_forward "$section" forward_upstream 1
-	if [ "$do_forward" = "1" ] ; then
-		local SERVERS
-		SERVERS=$(sed -ne 's/^nameserver \(.*\)/\1/p' /tmp/resolv.conf.auto | sort -u |head -n 4)
-		if [ "$SERVERS" ] ; then
-			if [ "$ignore_root_key" = "1"  ] ; then
-				echo "policy.add(policy.all(policy.STUB({">>$CONFIGFILE
-			else
-				echo "policy.add(policy.all(policy.FORWARD({">>$CONFIGFILE
+	config_get forward_dns "$section" forward_custom
+
+	#check custom forwarding
+	if [ -n "$forward_dns" ]; then
+		dns_config_load "$forward_dns"
+	else
+		if [ "$do_forward" = "1" ] ; then
+			local SERVERS
+			SERVERS=$(sed -ne 's/^nameserver \(.*\)/\1/p' /tmp/resolv.conf.auto | sort -u |head -n 4)
+			if [ "$SERVERS" ] ; then
+				if [ "$ignore_root_key" = "1"  ] ; then
+					echo "policy.add(policy.all(policy.STUB({">>$CONFIGFILE
+				else
+					echo "policy.add(policy.all(policy.FORWARD({">>$CONFIGFILE
+				fi
+				for SERVER in $SERVERS ; do
+					echo "	'$SERVER',">>$CONFIGFILE
+				done
+				echo "})))">>$CONFIGFILE
 			fi
-			for SERVER in $SERVERS ; do
-				echo "	'$SERVER',">>$CONFIGFILE
-			done
-			echo "})))">>$CONFIGFILE
 		fi
 		md5sum /tmp/resolv.conf.auto | cut -f1 -d\ >/tmp/resolv.conf.auto.last.md5
 	fi
@@ -197,13 +205,16 @@ add_hostname_config() {
 }
 
 modify_rundir() {
-        local rundir
-        local section="kresd"
+	local rundir
+	local section="kresd"
 
-        # rundir
-        config_get rundir "$section" rundir "$DEFAULT_RUNDIR"
-	[ ! -d "$rundir" ] && mkdir -p "$rundir"
-        DEFAULT_RUNDIR="$rundir"
+	#rundir
+	config_get rundir "$section" rundir "$DEFAULT_RUNDIR"
+	if [ ! -d "$rundir" ]; then
+		mkdir -p "$rundir"
+	fi
+	chown -R $USERNAME:$GROUP "$rundir" #maybe we should be more restrictive ...
+	DEFAULT_RUNDIR="$rundir"
 	HINTS_CONFIG=$DEFAULT_RUNDIR/hints.tmp
 }
 
@@ -252,7 +263,7 @@ run_instance() {
 	procd_set_param file /etc/config/resolver
 	procd_set_param command "$PROG"
 	procd_set_param respawn
-        modify_rundir
+	modify_rundir
 	init_header
 	load_uci_config_kresd
 	load_uci_config_common
@@ -264,6 +275,178 @@ run_instance() {
 		echo "net.ipv6 = false" | socat - UNIX-CONNECT:$(sleep 5; ls -1 $DEFAULT_RUNDIR/tty/*) > /dev/null 2>&1
 	  fi) &
 }
+
+
+dns_option_get() {
+	local ret_val var_name val
+	var_name=$1
+	config=$2
+
+	val=$(eval echo \$$1)
+	config_get ret_val "$config" "$var_name"
+
+	#rewrite variable if it's defined in uci
+	if [ ! -z "$ret_val" ]; then
+		eval export $var_name=\"$ret_val\"
+	fi
+}
+
+handle_dns_config_load() {
+	local name description enable_tls port ipv4 ipv6 pin_sha256 hostname
+	local net_ipv6 net_ipv4
+	local config="$1"
+	local config_name="$2"
+
+	config_get name "$config" "name"
+
+	#check config name (because of foreach function)
+	if [ "$name" != "$config_name" ]; then
+		echo -ne "ERR "
+		return 1
+	fi
+
+	#first load options from config and then eventualy
+	#rewrite set options from uci config
+
+	config_file=/etc/resolver/dns_servers/${config_name}.conf
+	if [ -f "$config_file" ]; then
+		source $config_file
+	fi
+
+	dns_option_get description $config
+	dns_option_get enable_tls $config
+	dns_option_get port $config
+	dns_option_get ipv4 $config
+	dns_option_get ipv6 $config
+	dns_option_get pin_sha256 $config
+	dns_option_get hostname $config
+
+	config_get net_ipv6 "common" "net_ipv6" 1
+	config_get net_ipv4 "common" "net_ipv4" 1
+
+	echo print_dns_config  "$name" "$description" "$enable_tls" "$port" "$ipv4" "$ipv6" "$pin_sha256" "$hostname" "$net_ipv4" "$net_ipv6"
+	print_dns_config  "$name" "$description" "$enable_tls" "$port" "$ipv4" "$ipv6" "$pin_sha256" "$hostname" "$net_ipv4" "$net_ipv6"
+
+	echo -ne "OK " #
+	return 0
+}
+
+
+print_dns_config() {
+	local name description enable_tls port ipv4 ipv6 pin_sha256 hostname
+	local net_ipv6 net_ipv4
+
+	name="$1"
+	description="$2"
+	enable_tls="$3"
+	port="$4"
+	ipv4="$5"
+	ipv6="$6"
+	pin_sha256="$7"
+	hostname="$8"
+	net_ipv4="$9"
+	net_ipv6="$10"
+
+
+	if   [ "$net_ipv4" == "1" ] && [ "$net_ipv6" == "1" ]; then
+		if [ ! -z "$ipv4" ] && [ ! -z "$ipv6" ]; then
+			ip_list="$ipv4 $ipv6"
+		elif [ ! -z "$ipv4" ] && [ -z "$ipv6" ]; then
+			ip_list="$ipv4"
+		elif [ -z "$ipv4" ] && [ ! -z "$ipv6" ]; then
+			ip_list="$ipv6"
+		else
+			echo "Error ipv4 and ipv6 not set !"
+			exit -1
+		fi
+	elif [ "$net_ipv4" == "0" ] && [ "$net_ipv6" == "1" ]; then
+		if [ ! -z "$ipv6" ]; then
+			ip_list="$ipv6"
+		else
+			echo "Error ipv6 not set !"
+			exit -1
+		fi
+	elif [ "$net_ipv4" == "1" ] && [ "$net_ipv6" = "0" ]; then
+		if [ ! -z "$ipv4" ]; then
+			ip_list="$ipv4"
+		else
+			echo "Error ipv4 not set !"
+			exit -1
+		fi
+	else
+		echo "net_ipv4=$net_ipv4 net_ipv6=$net_ipv6"
+		echo "Error cannot choose IP address because of net_ipv4 and net_ipv6 settings!"
+		exit -1
+	fi
+
+	#([ "$enable_tls" == "0" ] || [ -z "$enable_tls" ]) && echo -ne "{" >> $CONFIGFILE
+	if [ "$enable_tls" == "1" ]; then
+		echo "policy.add(policy.all(policy.TLS_FORWARD(">>$CONFIGFILE
+	else
+		echo "policy.add(policy.all(policy.FORWARD(">>$CONFIGFILE
+	fi
+	#TODO add stub !!
+
+	echo -ne "{" >> $CONFIGFILE
+	for ip in $ip_list
+	do
+
+		[ "$enable_tls" == "1" ] && echo -ne "{" >> $CONFIGFILE
+		if [ ! -z "$ip" ]; then
+			#check nonstandard port
+			if [ "$port" == "853" ] || [ -z "$port" ]; then
+				echo "'$ip'" >> $CONFIGFILE
+			else
+				echo "'$ip@$port'" >> $CONFIGFILE
+			fi
+
+			#check of DNS-over-TLS
+			if [ "$enable_tls" == "1" ]; then
+				#echo -ne "," >> $CONFIGFILE
+				#echo "hostname='$hostname'" >> $CONFIGFILE
+				echo -ne "," >> $CONFIGFILE
+				echo "pin_sha256='$pin_sha256'" >> $CONFIGFILE
+			fi
+		fi
+
+		last_item=$(echo $ip_list | awk '{print $NF}')
+		if [ "$enable_tls" == "1" ] && [ "$last_item" != "$ip" ] ; then
+			echo -ne "}," >> $CONFIGFILE
+		elif [ "$enable_tls" == "1" ] && [ "$last_item" == "$ip" ] ; then
+			echo -ne "}" >> $CONFIGFILE
+		elif ([ "$enable_tls" == "0" ] || [ -z "$enable_tls" ]) && [ "$last_item" != "$ip" ]; then
+			echo -ne "," >> $CONFIGFILE
+		fi
+	done
+	echo -ne "}" >> $CONFIGFILE
+	echo ")))" >>$CONFIGFILE
+}
+
+dns_config_load() {
+	local config_name config_file ret
+	local name description enable_tls port ipv4 ipv6 pin_sha256 hostname
+	local net_ipv4 net_ipv6
+
+	config_name="$1"
+	config_file="/etc/resolver/dns_servers/${config_name}.conf"
+	config_load resolver
+	ret=$(config_foreach handle_dns_config_load dns_server "$config_name")
+
+
+	#uci part nof found, check file
+	if [ "$?" == "1" ] && [ -f "$config_file" ]; then
+		enable_tls="0" #set default value
+		config_get net_ipv6 "common" "net_ipv6" 1
+		config_get net_ipv4 "common" "net_ipv4" 1
+
+		echo "loading file from ... $config_file"
+		source $config_file
+		echo print_dns_config  "$name" "$description" "$enable_tls" "$port" "$ipv4" "$ipv6" "$pin_sha256" "$hostname" "$net_ipv4" "$net_ipv6"
+		print_dns_config  "$name" "$description" "$enable_tls" "$port" "$ipv4" "$ipv6" "$pin_sha256" "$hostname" "$net_ipv4" "$net_ipv6"
+	fi
+	echo "ret_value_dns_load=$ret"
+}
+
 
 start_service() {
 	config_load resolver
