switch-branch: update it to be compatible with 4.x

diff --git a/cznic/switch-branch/files/switch-branch b/cznic/switch-branch/files/switch-branch
--- a/cznic/switch-branch/files/switch-branch
+++ b/cznic/switch-branch/files/switch-branch
@@ -1,29 +1,38 @@
 #!/bin/sh
 set -e
+# TODO notest on what to add:
+# * --latest option that in combination with --version automatically sets latest release
+# * --list-versions option that allows any external script to list all available versions
 
-BRANCH=
-VERIFY=false
-FORCE=false
+branch=
+version=false
+verify=false
+force=false
 while [ $# -gt 0 ]; do
 	case "$1" in
 		-h|--help)
-			echo "Script for easier branch switching."
 			echo "Usage: switch-branch [OPTION]... [BRANCH]"
+			echo "Script for easier switching between rolling versions of Turris OS."
+			echo "It configures both updater-ng and opkg repository source."
 			echo
 			echo "Options:"
-			echo "  --verify Verify and fix branch settings"
-			echo "  --force  "
-			echo "  --help   Print this help text"
+			echo "  --version  Instead of switching to branch switch to fixed version"
+			echo "  --verify   Verify and fix branch/version settings (apply setting from uci updater.turris)"
+			echo "  --force    Change to unknown (not-existing) branch/version"
+			echo "  --help     Print this help text"
 			exit 0
 			;;
+		--version)
+			version=true
+			;;
 		--verify)
-			VERIFY=true
+			verify=true
 			;;
 		--force)
-			FORCE=true
+			force=true
 			;;
 		*)
-			BRANCH="$1"
+			branch="$1"
 			;;
 	esac
 	shift
@@ -46,127 +55,277 @@ if ! which updater.sh >/dev/null 2>&1; then
 	exit 1
 fi
 
+# Fetch all existing versions
+if $version; then
+	versions="$(curl "https://repo.turris.cz/archive/" | \
+		sed -n 's|.*alt="\[DIR\]".*<a href="\([^"]*\)/".*|\1|p' | \
+		grep -Ev "^(omnia|turris|3.x)$" | sort -r)"
+fi
+
 # Return current branch
 get_branch() {
-	uci get updater.override.branch 2>/dev/null || echo "deploy"
+	uci get updater.turris.branch 2>/dev/null || echo "hbs"
+}
+# Return current version
+get_version() {
+	uci get updater.turris.version 2>/dev/null || cat /etc/turris-version
+}
+# Check if we should use version (or branch)
+use_version() {
+	uci get updater.turris.version >/dev/null 2>&1
+}
+# This returns latest stable version (the only one that is supported)
+latest_version() {
+	echo "$versions" | head -1
+}
+
+# We allows some branch alternatives. This function replaces them with canon versions
+branch_alts() {
+	case "$branch" in
+		snails)
+			branch='hbs'
+			;;
+		turtles)
+			branch='hbt'
+			;;
+		kittens)
+			branch='hbk'
+			;;
+		dragons)
+			branch='hbd'
+			;;
+	esac
 }
 
 # Checks if branch is supported (accept any branch if forced, otherwise only the
 # selected ones)
 check_branch() {
-	$FORCE || echo "$BRANCH" | grep -qE '^(deploy|rc|prerc|daily|nightly|test)$'
+	$force || echo "$branch" | grep -qE '^(hbd|hbk|hbt|hbs)$'
+}
+# Check if given version is valid/existing version (force again allows usage of
+# any version)
+check_version() {
+	$force || echo "$versions" | grep -qxF "$branch"
 }
 
-# Get branch from uci in case of no branch is specified and verification
-if $VERIFY && [ -z "$BRANCH" ]; then
-	BRANCH="$(get_branch)"
+# Get branch from uci in case of no branch is specified and veryfication
+if $verify && [ -z "$branch" ]; then
+	branch="$(get_branch)"
 fi
 
-# Interactive selection of branch
-while [ -z "$BRANCH" ]; do
-	# Note: branch prerc is not here as it's mostly for internal use only
-cat <<EOF
+# If branch provided then verify it
+if [ -n "$branch" ]; then
+	if $version; then
+		if ! check_version; then
+			echo "Version $branch seems to not be existing released version!" >&2
+			exit 1
+		fi
+	else
+		branch_alts
+		if ! check_branch; then
+			echo "Branch $branch isn't supported branch!" >&2
+			exit 1
+		fi
+	fi
+fi
+
+# Interactive selection of branch if branch was not yet set
+while [ -z "$branch" ]; do
+	if $version; then
+		echo
+		echo "You are using version: $(get_version)"
+		echo
+		echo "Following latest versions are available:"
+		echo "$versions" | head -10 | sed 's/^/  /'
+		echo "Note that only latest release is supported!"
+		echo -n "Please enter version: "
+		read -r branch
+		check_version || {
+			echo "Version seems to be not existing released version: $branch"
+			echo
+			branch=
+		}
+	else
+		cat <<EOF
 You are currently in: $(get_branch)
 
-You can choose from one of these branches:
-  deploy
-    Default and most stable branch. Suggested for unexperienced users.
-  rc
-    Release candidate. This branch contains next Turris OS release. Please join
-    this branch to help us test next release. It's more stable than daily but it
-    can contain bugs.
-  daily
-    This branch is same as nightly except it is updated only when automatic
-    tests are successful. Should be more stable than nightly but manual
-    intervention might be sometimes required too.
-  nightly
-    Branch built every night containing latest software. Suggested only for
-    experienced users as it's sometimes broken and requires manual intervention.
-  test
-    Branch used during development. It's often broken. It's usage is highly
-    discouraged.
+You can choose from one of these rolling releases:
+  hbs (snails)
+    The default and most stable rolling release. Suggested for unexperienced
+    users and for critical infrastructure.
+  hbt (turtles)
+    This rolling release contains next sloths version. Please join this branch to
+    help us test it and to get new stuff few weeks up-front.
+  hbk (kittens)
+    This rolling release tracks stable OpenWRT upstream and contains latest Turris
+    development. Manual intervention might be sometimes required to fix introduced
+    bugs and because of that it is suggested to be used only by experienced users.
+  hbd (dragons)
+    This rolling release not only tracks latest Turris but also latest OpenWRT
+    development. It can frequently break and is suggested to be used only by
+    experienced users on non-critical infrastructure.
 EOF
-	echo -n "Please enter name of a branch branch: "
-	read BRANCH
-	check_branch || BRANCH=
+		echo -n "Please enter name of a branch branch: "
+		read -r branch
+		branch_alts
+		check_branch || {
+			echo "There is no known branch: $branch"
+			echo
+			branch=
+		}
+	fi
 done
 
-if ! check_branch; then
-	echo "Branch $BRANCH isn't supported branch!" >&2
-	exit 1
+# For test branches install test keys
+if \! $version; then
+	case "$branch" in
+		hbs|hbk)
+			# We don't have to remove cznic-repo-keys-test as it's removed automaticaly by updater
+			;;
+		*)
+			# We should not use opkg to check for installed packages because it requires its lock which makes this tool impossible to use from install scripts
+			if [ ! -f /usr/lib/opkg/info/cznic-repo-keys-test.control ]; then # If not installed
+				# We use opkg-cl instead of opkg to bypass updater wrapper and not to add it to /etc/updater/auto.lua
+				opkg-cl update
+				opkg-cl install cznic-repo-keys-test
+			fi
+			;;
+	esac
 fi
 
 set -x
 
-## Install test keys if we need it
-case "$BRANCH" in
-	deploy|rc)
-		# We don't have to remove cznic-repo-keys-test as it's removed automaticaly by updater
-		;;
-	*)
-		# We should not use opkg to check for installed packages because it requires its lock which makes this tool impossible to use from install scripts
-		if [ ! -f /usr/lib/opkg/info/cznic-repo-keys-test.control ]; then # If not installed
-			# We use opkg-cl instead of opkg to bypass updater wrapper and not to add it to /etc/updater/auto.lua
-			opkg-cl update
-			opkg-cl install cznic-repo-keys-test
-		fi
-		;;
-esac
+## Set uci configuration
+uci set updater.turris=turris
+if $version; then
+	uci set updater.turris.mode="version"
+	uci set updater.turris.version="$branch"
+else
+	uci set updater.turris.mode="branch"
+	uci set updater.turris.branch="$branch"
+fi
+uci commit updater.turris
 
 ## Tweak opkg distribution feeds
-[ "$BRANCH" = "deploy" ] && VBRANCH="" || VBRANCH="-$BRANCH"
-sed -i "/\(turris\|omnia\)_nightly_/d;s#\(https://repo\.turris\.cz/\(turris\|omnia\)\)[^/]*/#\1$VBRANCH/#" /etc/opkg/distfeeds.conf # Note that this sed also removes all nightly fallbacks
-case "$BRANCH" in
-	test|dev-*) # for non-full branches add nightly as fallback
-		TFD="$(mktemp)"
-		cat /etc/opkg/distfeeds.conf > "$TFD"
-		sed "/\(turris\|omnia\)_/!d;s#\(turris\|omnia\)_#\1_nightly_#;s#\(https://repo\.turris\.cz/\(turris\|omnia\)\)[^/]*/#\1-nightly/#" /etc/opkg/distfeeds.conf >> "$TFD"
-		mv "$TFD" /etc/opkg/distfeeds.conf
-		;;
-esac
-
-## Set uci configuration
-uci set updater.override=override
-[ "$BRANCH" = "deploy" ] && VBRANCH="" || VBRANCH="$BRANCH"
-uci set updater.override.branch="$VBRANCH"
-uci commit updater.override.branch
+if $version; then
+	sed -i "s#https://repo\.turris\.cz/.*/packages/#https://repo\.turris\.cz/archive/$branch/packages/#" /etc/opkg/distfeeds.conf
+else
+	sed -i "s#https://repo\.turris\.cz/.*/packages/#https://repo\.turris\.cz/$branch/packages/#" /etc/opkg/distfeeds.conf
+fi
 
 # If we are verifying configuration than the work is done.
 # We don't want to run updater nor printing info about branch.
-if $VERIFY; then
+if $verify; then
 	exit 0
 fi
 
 ## Run updater
-UPDATER_ARGS=
-[ "$(uci get "updater.approvals.need" 2>/dev/null)" = "1" ] || UPDATER_ARGS="--batch"
-pkgupdate $UPDATER_ARGS || echo "Updater execution exited with error. Please see previous output to know what went wrong." >&2
+updater_args=
+[ "$(uci get "updater.approvals.need" 2>/dev/null)" = "1" ] || updater_args="--batch"
+pkgupdate $updater_args || echo "Updater execution exited with error. Please see previous output to know what went wrong." >&2
+
+## Update opkg
+opkg update
 
 set +x
 
-# Print some info about new branch
+print_snail() {
+	cat <<"EOF"
+    .----.   @   @
+   / .-"-.`.  \v/
+   | | '\ \ \_/ )
+ ,-\ `-.' /.'  /
+'---`----'----'
+EOF
+}
+
+print_turtle() {
+	cat <<"EOF"
+                __
+     .,-;-;-,. /'_\
+   _/_/_/_|_\_\) /
+ '-<_><_><_><_>=/\
+   `/_/====/_/-'\_\
+    ""     ""    ""
+EOF
+}
+
+print_kitten() {
+	cat <<"EOF"
+("`-''-/").___..--''"`-._
+ `6_ 6  )   `-.  (     ).`-.__.`)
+ (_Y_.)'  ._   )  `._ `. ``-..-'
+   _..`--'_..-_/  /--'_.'
+  ((((.-''  ((((.'  (((.-'
+EOF
+}
+
+print_dragon() {
+	cat <<"EOF"
+                \||/
+                |  @___oo
+      /\  /\   / (__,,,,|
+     ) /^\) ^\/ _)
+     )   /^\/   _)
+     )   _ /  / _)
+ /\  )/\/ ||  | )_)
+<  >      |(,,) )__)
+ ||      /    \)___)\
+ | \____(      )___) )___
+  \______(_______;;; __;;;
+EOF
+}
+
+
+# Print some info about new version
 echo
-case "$BRANCH" in
-	deploy)
-		echo "You are now in the most stable branch." >&2
-		echo "With problems please contact Turris support (https://doc.turris.cz/doc/en/howto/error_reporting)." >&2
-		;;
-	rc|prerc)
-		echo "You are now in branch containing next release candidate." >&2
-		echo "You can discuss problems on forum (https://forum.turris.cz)." >&2
-		echo "Please report unknown problems to support (https://doc.turris.cz/doc/en/howto/error_reporting)." >&2
-		;;
-	nightly|daily)
-		# TODO split off daily when we have some support for it
-		echo "You are now in branch containing software build every night. It often contains bugs and sometimes requires manual intervention!" >&2
-		echo "Turris team provides no guarantees and no support for this branch. You can get some help on forum (https://forum.turris.cz/)." >&2
-		echo "If you encounter some bugs than please debug cause and report it to developers trough gitlab (https://gitlab.labs.nic.cz/)," >&2
-		echo "You shouldn't be in this branch unless you are advanced user!" >&2
-		echo "To return to deploy run this command: switch-branch deploy" >&2
-		;;
-	*) # test and any other branch
-		echo "You are now in development branch. Unless you are developer you shouldn't use this branch!" >&2
-		echo "Turris team provides no guarantees and no support for this branch." >&2
-		echo "To return to deploy run this command: switch-branch deploy" >&2
-		;;
-esac
+if $version; then
+	if [ "$branch" = "$(latest_version)" ]; then
+		echo "You are using now latest stable version of Turris OS." >&2
+		echo "If you encounter some problems please contact Turris support (https://doc.turris.cz/doc/en/howto/error_reporting)." >&2
+		echo "Note that this version is only supported by Turris support until new stable release is released." >&2
+		echo "Do not forget to come back and switch to newer version when it is released!" >&2
+	else
+		echo "You are now using one of the older versions of Turris OS." >&2
+		echo "Old versions are not supported!" >&2
+		echo "Please switch to rolling branch or to latest branch as soon as possible!" >&2
+		echo "To switch to latest stable branch use: switch-branch hbs" >&2
+	fi
+else
+	case "$branch" in
+		hbs)
+			print_snail
+			echo "You are now on stable latest version of Turris OS." >&2
+			echo "With problems please contact Turris support (https://doc.turris.cz/doc/en/howto/error_reporting)." >&2
+			;;
+		hbt)
+			print_turtle
+			echo "You are now in branch containing next release candidate." >&2
+			echo "You can discuss problems on forum (https://forum.turris.cz)." >&2
+			echo "Please report unknown problems to support (https://doc.turris.cz/doc/en/howto/error_reporting)." >&2
+			;;
+		hbk)
+			print_kitten
+			echo "You are now in branch containing software build every night. It often contains bugs and sometimes requires manual intervention!" >&2
+			echo "It is based on latest stable OpenWRT branch with latest Turris OS changes." >&2
+			echo "Turris team provides no guarantees and no support for this branch. You can get some help on forum (https://forum.turris.cz/)." >&2
+			echo "If you encounter some bugs than please debug cause and report it to developers trough gitlab (https://gitlab.labs.nic.cz/)," >&2
+			echo "You shouldn't be in this branch unless you are advanced user!" >&2
+			echo "To return to stable branch run this command: switch-branch hbs" >&2
+			;;
+		hbd)
+			print_dragon
+			echo "You are now in branch containing software build every night. It often contains bugs and very often requires manual intervention!" >&2
+			echo "It is based on latest OpenWRT development branch with latest Turris OS changes." >&2
+			echo "Turris team provides no guarantees and no support for this branch. You can get some help on forum (https://forum.turris.cz/)." >&2
+			echo "If you encounter some bugs than please debug cause and report it to developers trough gitlab (https://gitlab.labs.nic.cz/)," >&2
+			echo "You shouldn't be in this branch unless you are advanced user and OpenWRT developer!" >&2
+			echo "To return to stable branch run this command: switch-branch hbs" >&2
+			;;
+		*)
+			echo "You are now in unknown version. Unless you are a developer you shouldn't use this branch!" >&2
+			echo "Turris team provides no guarantees and no support for this branch." >&2
+			echo "To return to stable branch run this command: switch-branch hbs" >&2
+			;;
+	esac
+fi
