Add a if-else statement which checks for exit status of every init script.

diff --git a/cznic/rescue-mode/files/etc/init.d/rcS b/cznic/rescue-mode/files/etc/init.d/rcS
--- a/cznic/rescue-mode/files/etc/init.d/rcS
+++ b/cznic/rescue-mode/files/etc/init.d/rcS
@@ -1,8 +1,15 @@
 #!/bin/sh
 
-echo Run scripts 
+echo "CZ.NIC init"; echo
 
 for i in /etc/rc.d/$1*; do
         [ -x $i ] && $i $2 2>&1
+        RET=$?
+        if [ $RET == 0 ]; then
+                echo "$i        [done]"
+        else
+                echo "$i        [fail!]"
+        fi        
+
 done
 
